### ISSUE TITLE
Probably my own problem

### ISSUE THREAD

**Issue by jhicken** [MThoma202/prosper-1099-parser#5]
I ran this
`./gradlew clientInstall bootRun`
Picked up JAVA_TOOL_OPTIONS: -Dhttps.protocols=TLSv1.2

FAILURE: Build failed with an exception.

* Where:
Build file '/<path>/prosper-1099-parser/build.gradle' line: 21

* What went wrong:
Plugin [id: 'com.craigburke.client-dependencies', version: '1.4.0'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'com.craigburke.client-dependencies:com.craigburke.client-dependencies.gradle.plugin:1.4.0')
  Searched in the following repositories:
    Gradle Central Plugin Repository

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.5.1/userguide/command_line_interface.html#sec:command_line_warnings

Its also worth noting that I had to set this env var.
JAVA_TOOL_OPTIONS: -Dhttps.protocols=TLSv1.2

I'm a java noob. Do I need to downgrade Gradle or run something separate to install the missing dependency?

**Comment by MThoma202** [comment]
@jhicken Thanks for reporting this. I'm not 100% sure why this doesn't work for you but I just pushed a fix for this.  The client-dependencies plugin is hosted by multiple maven repositories but I updated it to find it in the Gradle Central Plugin Repository.

Can you please run `git pull` to get the latest and then try again? Please let me know if it's still happening.  Also just curious, what operating system and version are you running this on (macOS, Windows, linux)?  Also what version of Java do you have installed?  If you run `java -version` it should print it.

**Comment by MThoma202** [comment]
@jhicken Actually what I changed might not fix the problem.  If it doesn't work can you please try downloading/installing the latest 1.8 JDK for your OS and try again? I'm still curious to know what version you're currently using though.  https://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

**Comment by jhicken** [comment]
Awe crap I feel silly now. I had installed the JDK 1.8.x but I forgot to change the JAVA_HOME path in my `.bashrc`.  So it was using 1.7.x. Also I'm on osx. Once I changed the JDK version correctly voila. It worked beautifully. Thanks for your work on this! It will make reporting tax on this sooooo much simpler.
